POST http://localhost:3000/board/create
Content-Type: application/json

{
  "title": "nestjs board",
  "description": "nestjs 게시판 만들기"
}

###
GET http://localhost:3000/board/get-all
Accept: application/json

###
