# Board
POST http://localhost:3000/board/create
Content-Type: application/json

{
  "title": "nestjs board5",
  "description": "nestjs 게시판 만들기5"
}

###
GET http://localhost:3000/board/get-all
Accept: application/json

###
GET http://localhost:3000/board/get?id=5
Accept: application/json

###
GET http://localhost:3000/board/5
Accept: application/json

###
DELETE http://localhost:3000/board/3

###
PATCH http://localhost:3000/board/5/status
Content-Type: application/json

{
  "status": "PRIVATE"
}
###

# User
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "username": "robbie",
  "password": "1234"
}

###







